# Generated by Django 5.1.5 on 2025-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('watch', models.ManyToManyField(null=True, to='relations.video')),
            ],
        ),
    ]
